Issue #498 - Update MovieManagerUI.js
Helioviewer-Project/helioviewer.org pull request #512
Opened 2023-12-06 16:22 UTC by raptor-07

Datepicker for advanced movie options blocks out dates that it shouldn't.

'maxDate' option defaults to null.
reference: https://flatpickr.js.org/options/

The option has been removed from flatpickr instance. This allows user to select future dates.

2023-12-06 16:41 UTC, dgarciabriseno requested changes
Thanks for the PR!
Can you remove the whole onOpen function?

2023-12-06 16:41 UTC, dgarciabriseno commented on resources/js/Media/MovieManagerUI.js
>  			}
Remove the whole onOpen function since all it was doing was limiting the date.

2023-12-06 16:44 UTC, dgarciabriseno commented on resources/js/Media/MovieManagerUI.js
>  			}
Can you also remove the onOpen function on line 434, it's doing the same thing, but for minDate.

2023-12-06 17:52 UTC, raptor-07 commented on resources/js/Media/MovieManagerUI.js
>  			}
Please check latest commit!

2023-12-14 13:31 UTC, merged

2023-12-14 13:31 UTC, dgarciabriseno commented
Thanks for the PR!