Fix/toggle event buttons should work only for their layer
Helioviewer-Project/helioviewer.org pull request #552
Opened 2024-05-10 19:51 UTC by mudhoney

# Summary

- Maintain all event layer visibility states separately, 
- All buttons of event layers are working with their state and preserved in localStorage state.
- Remove all global state of visibility and remove all related codes
- 'd' button is still usable
- remembers all labels state and works correctly with the output minimal
- correctly works with movie and screenshot makers, handle them as before

# Testing

Enter the browsers and the output modes (minimal, normal, embed) this change was tested

| *browser* | *normal* | *minimal* | *embed* | 
| ------- | -------- | -------- | -------- |
| firefox | untested | untested | untested |
| chrome  | tested | tested | untested |
| safari  | untested | untested | untested |
| edge    | untested | untested | untested |

2024-05-13 17:13 UTC, dgarciabriseno requested changes

2024-05-13 17:13 UTC, dgarciabriseno commented on resources/js/Events/EventManager.js
> +     * @param {array} eventGlossaryyy
yyy.

Thank you for adding parameter docs

2024-05-13 17:13 UTC, dgarciabriseno commented on resources/js/Events/EventManager.js
> +                        // For each event markers of frm , we are making them visible if they are not hided per user preferences via state
```suggestion
                        // For each event markers of frm, we are making them visible if they are not hidden per user preferences via state
```

2024-05-13 17:13 UTC, dgarciabriseno commented on resources/js/Events/EventManager.js
Can you add a comment above `_toggleEvents` to explain when this function gets called?

2024-05-13 17:13 UTC, dgarciabriseno commented on resources/js/Events/EventManager.js
> +     * @returns boolean
```suggestion
     * @returns {boolean}
```

2024-05-13 17:13 UTC, dgarciabriseno commented on resources/js/Events/EventMarker.js
> +     * @param {boolean} labelVisible, set if the labels of this marker is hided
```suggestion
     * @param {integer} zIndex, zIndex as you know, visibility hierarchy of this marker in html
     * @param {boolean} labelVisible, set if the labels of this marker is hidden
```

2024-05-13 17:13 UTC, dgarciabriseno commented on resources/js/Events/EventTree.js
> +     * @param {integer} zIndex, zIndex as you know , visibility hierarchy of this marker in html
```suggestion
     * @param {dom} container, dom piece to append event tree dom
     * @param {EventManager} eventManager, event manager this tree is managed by
     * @param {integer} zIndex, zIndex as you know, visibility hierarchy of this marker in html
```

2024-05-13 17:13 UTC, dgarciabriseno commented on resources/js/Events/EventTree.js
> +     * @description toggles the visibility of frm nodes is tree , if they are not have any child nides
```suggestion
     * @description toggles the visibility of frm nodes is tree, if they do not have any child nodes
```

2024-05-13 17:13 UTC, dgarciabriseno commented on resources/js/Events/HelioviewerEventLayerManager.js
>      },
Does this function get used anywhere? Can it be removed?

This looks like it was supposed to be `_loadStartingLayers`, maybe dead code.

2024-05-13 20:42 UTC, mudhoney commented on resources/js/Events/HelioviewerEventLayerManager.js
>      },
Absolutely! I tracked it down and removed it with some dead events as well , 
https://github.com/Helioviewer-Project/helioviewer.org/pull/552/commits/049eab58d42356b43f91fbc5acd69e3e92847dc6

2024-05-14 13:08 UTC, dgarciabriseno approved these changes

2024-05-14 13:08 UTC, dgarciabriseno commented on resources/js/Events/EventLayerManager.js
> -        this.removeLayer(id);
I love deleting code

2024-05-14 13:22 UTC, mudhoney commented on resources/js/Events/EventLayerManager.js
> -        this.removeLayer(id);
me too 👍

2024-05-14 15:54 UTC, merged